### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Pyrrvs** [supercast-tv/python-mpd-parser#2]
Hi,

I've been digging into your MPD parser and found it really convenient ! I was wondering under which license you were distributing it. I would not like to steal your work by mistake !

Thank you for your awesome work,
Gauthier Lamaison

**Comment by sangwonl** [comment]
Thanks for your comment. Sure, you can use it without any limitation. If you want to put more things, welcomed! :)

Anyway, I will specify the license.

**Comment by Pyrrvs** [comment]
Thanks a lot! :)
